import type { HeroSlide, ImpactStat, Program, Story, Testimonial, TimelineEvent } from "./types";
import heroChildren from "@/assets/hero-children.jpg";
import heroElderly from "@/assets/hero-elderly.jpg";
import programChildren from "@/assets/program-children.jpg";
import programElderly from "@/assets/program-elderly.jpg";
import programEmpowerment from "@/assets/program-empowerment.jpg";

export const fallbackHeroSlides: HeroSlide[] = [
  {
    id: "fallback-hero-1",
    title: "Restoring dignity, one life at a time.",
    subtitle: "A humanitarian bridge between Europe and Nigeria, bringing hope to vulnerable children, the elderly, and women in need.",
    image_url: heroChildren,
    cta_text: "Donate Now",
    cta_link: "/donate",
    order: 0,
    is_active: true,
    created_at: "",
  },
  {
    id: "fallback-hero-2",
    title: "Every child deserves a home.",
    subtitle: "We provide safe shelter, education, and loving care for children who have lost their families.",
    image_url: heroChildren,
    cta_text: "Our Programs",
    cta_link: "/programs",
    order: 1,
    is_active: true,
    created_at: "",
  },
  {
    id: "fallback-hero-3",
    title: "No elder should be forgotten.",
    subtitle: "Daily meals, medical visits, and companionship for seniors living alone across Nigeria.",
    image_url: heroElderly,
    cta_text: "Volunteer",
    cta_link: "/volunteer",
    order: 2,
    is_active: true,
    created_at: "",
  },
];

export const fallbackStories: Story[] = [
  {
    id: "fallback-story-1",
    slug: "chiamaka-found-her-way-back-to-school",
    title: "How Chiamaka found her way back to school",
    excerpt: "After losing both parents, Chiamaka's future looked uncertain. Today, she's top of her class.",
    content: "After losing both parents, Chiamaka's future looked uncertain. Through the Motherless Homes program, she found a safe home, school sponsorship, and mentors who believed in her. Today, she's top of her class and dreams of becoming a doctor.",
    image_url: programChildren,
    author_name: "Eagle's Wings Team",
    published_at: "2024-09-15T00:00:00Z",
    is_active: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "fallback-story-2",
    slug: "baba-sules-wednesday-smile",
    title: "Baba Sule's Wednesday smile",
    excerpt: "A weekly visit became the highlight of his week — and ours.",
    content: "Baba Sule lives alone in a small village outside Enugu. Every Wednesday, our Elderly Care team brings him a hot meal, checks his blood pressure, and sits with him to hear stories from his youth. That weekly visit has become the highlight of his week — and ours.",
    image_url: programElderly,
    author_name: "Eagle's Wings Team",
    published_at: "2024-10-02T00:00:00Z",
    is_active: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "fallback-story-3",
    slug: "halimas-first-shop",
    title: "From trainee to tailor: Halima's first shop",
    excerpt: "Six months of training, one micro-grant, and an entirely new chapter.",
    content: "Halima joined our empowerment program with a passion for fashion but no tools. After six months of tailoring training and a micro-grant for a sewing machine, she opened her first shop. She now employs two other young women from her community.",
    image_url: programEmpowerment,
    author_name: "Eagle's Wings Team",
    published_at: "2024-11-20T00:00:00Z",
    is_active: true,
    created_at: "",
    updated_at: "",
  },
];

export const fallbackTimeline: TimelineEvent[] = [
  {
    id: "fallback-timeline-1",
    year: "2016",
    title: "A spark in Lagos",
    description: "Our founder began visiting motherless homes with home-cooked meals and school supplies.",
    order: 0,
    created_at: "",
  },
  {
    id: "fallback-timeline-2",
    year: "2018",
    title: "First shelter opened",
    description: "We opened our first community home for 22 children in Enugu State.",
    order: 1,
    created_at: "",
  },
  {
    id: "fallback-timeline-3",
    year: "2021",
    title: "Europe chapter",
    description: "Berlin-based partners and donors joined the mission, formalizing our cross-continental bridge.",
    order: 2,
    created_at: "",
  },
  {
    id: "fallback-timeline-4",
    year: "2023",
    title: "Elderly care launch",
    description: "Daily meal & medical visits for forgotten seniors across three communities.",
    order: 3,
    created_at: "",
  },
];

export const fallbackImpactStats: ImpactStat[] = [
  { id: "fallback-1", label: "Children supported", value: 1240, suffix: "+", icon: "users", order: 0, is_active: true, created_at: "" },
  { id: "fallback-2", label: "Elderly cared for", value: 380, suffix: "+", icon: "heart", order: 1, is_active: true, created_at: "" },
  { id: "fallback-3", label: "Volunteers engaged", value: 95, suffix: "+", icon: "hand-heart", order: 2, is_active: true, created_at: "" },
  { id: "fallback-4", label: "Communities served", value: 12, suffix: "", icon: "map-pin", order: 3, is_active: true, created_at: "" },
];

export const fallbackPrograms: Program[] = [
  {
    id: "fallback-program-1",
    slug: "motherless-home",
    title: "Motherless Homes",
    subtitle: "A family for every child without one.",
    summary: "Safe shelter, education, and family for children who have lost everything.",
    description: "Our community homes provide safe shelter, three meals a day, school enrollment and consistent loving care for children who have lost their parents. We don't run orphanages — we run families.",
    image_url: programChildren,
    icon: "home",
    order: 0,
    is_active: true,
    meta_title: "Motherless Homes Program — Eagle's Wings Empowerment",
    meta_description: "We give vulnerable children in Nigeria shelter, education, and a family that loves them.",
    created_at: "",
    updated_at: "",
  },
  {
    id: "fallback-program-2",
    slug: "elderly-care",
    title: "Elderly Care",
    subtitle: "Walking beside our elders with dignity and love.",
    summary: "Daily meals, medical visits and companionship for seniors who are alone.",
    description: "Many elderly Nigerians live alone, without family or income. Our trained caregivers visit weekly with hot meals, medical check-ins, and the simple gift of presence.",
    image_url: programElderly,
    icon: "heart",
    order: 1,
    is_active: true,
    meta_title: "Elderly Care Program — Eagle's Wings Empowerment",
    meta_description: "Dignified care, meals, and medical support for lonely seniors in Nigeria.",
    created_at: "",
    updated_at: "",
  },
  {
    id: "fallback-program-3",
    slug: "empowerment",
    title: "Women & Youth Empowerment",
    subtitle: "Skills, capital, and confidence to build a future.",
    summary: "Vocational training, micro-grants, and mentorship for women and young people.",
    description: "We provide vocational training, small business grants, and one-on-one mentorship so women and youth can support themselves and their families with dignity.",
    image_url: programEmpowerment,
    icon: "briefcase",
    order: 2,
    is_active: true,
    meta_title: "Women & Youth Empowerment — Eagle's Wings Empowerment",
    meta_description: "Vocational training, micro-grants, and mentorship for women and youth in Nigeria.",
    created_at: "",
    updated_at: "",
  },
];

export const fallbackTestimonials: Testimonial[] = [
  {
    id: "fallback-testimonial-1",
    quote: "Eagle's Wings gave my grandchildren a chance I could never afford. They are now in school, fed, and full of hope.",
    author_name: "Mama Ngozi",
    author_role: "Beneficiary, Enugu",
    author_image_url: "",
    order: 0,
    is_active: true,
    created_at: "",
  },
  {
    id: "fallback-testimonial-2",
    quote: "Donating monthly from Berlin felt small until I visited and saw the home my contributions helped build. Real, transparent impact.",
    author_name: "Lukas Berger",
    author_role: "Donor, Germany",
    author_image_url: "",
    order: 1,
    is_active: true,
    created_at: "",
  },
  {
    id: "fallback-testimonial-3",
    quote: "Volunteering here changed how I see service. The dignity they bring to every elder is something I'll carry forever.",
    author_name: "Amaka O.",
    author_role: "Volunteer, Lagos",
    author_image_url: "",
    order: 2,
    is_active: true,
    created_at: "",
  },
];
