/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as ProgramsMotherlessHomeRouteImport } from './routes/programs.motherless-home'
import { Route as ProgramsEmpowermentRouteImport } from './routes/programs.empowerment'
import { Route as ProgramsElderlyCareRouteImport } from './routes/programs.elderly-care'
import { Route as DonateVerifyRouteImport } from './routes/donate.verify'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const ProgramsMotherlessHomeRoute = ProgramsMotherlessHomeRouteImport.update({
  id: '/motherless-home',
  path: '/motherless-home',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsEmpowermentRoute = ProgramsEmpowermentRouteImport.update({
  id: '/empowerment',
  path: '/empowerment',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsElderlyCareRoute = ProgramsElderlyCareRouteImport.update({
  id: '/elderly-care',
  path: '/elderly-care',
  getParentRoute: () => ProgramsRoute,
} as any)
const DonateVerifyRoute = DonateVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DonateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/volunteer': typeof VolunteerRoute
  '/donate/verify': typeof DonateVerifyRoute
  '/programs/elderly-care': typeof ProgramsElderlyCareRoute
  '/programs/empowerment': typeof ProgramsEmpowermentRoute
  '/programs/motherless-home': typeof ProgramsMotherlessHomeRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/volunteer': typeof VolunteerRoute
  '/donate/verify': typeof DonateVerifyRoute
  '/programs/elderly-care': typeof ProgramsElderlyCareRoute
  '/programs/empowerment': typeof ProgramsEmpowermentRoute
  '/programs/motherless-home': typeof ProgramsMotherlessHomeRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/volunteer': typeof VolunteerRoute
  '/donate/verify': typeof DonateVerifyRoute
  '/programs/elderly-care': typeof ProgramsElderlyCareRoute
  '/programs/empowerment': typeof ProgramsEmpowermentRoute
  '/programs/motherless-home': typeof ProgramsMotherlessHomeRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/programs'
    | '/stories'
    | '/volunteer'
    | '/donate/verify'
    | '/programs/elderly-care'
    | '/programs/empowerment'
    | '/programs/motherless-home'
    | '/stories/$slug'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/stories'
    | '/volunteer'
    | '/donate/verify'
    | '/programs/elderly-care'
    | '/programs/empowerment'
    | '/programs/motherless-home'
    | '/stories/$slug'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/programs'
    | '/stories'
    | '/volunteer'
    | '/donate/verify'
    | '/programs/elderly-care'
    | '/programs/empowerment'
    | '/programs/motherless-home'
    | '/stories/$slug'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRouteWithChildren
  ProgramsRoute: typeof ProgramsRouteWithChildren
  StoriesRoute: typeof StoriesRouteWithChildren
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/programs/motherless-home': {
      id: '/programs/motherless-home'
      path: '/motherless-home'
      fullPath: '/programs/motherless-home'
      preLoaderRoute: typeof ProgramsMotherlessHomeRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/empowerment': {
      id: '/programs/empowerment'
      path: '/empowerment'
      fullPath: '/programs/empowerment'
      preLoaderRoute: typeof ProgramsEmpowermentRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/elderly-care': {
      id: '/programs/elderly-care'
      path: '/elderly-care'
      fullPath: '/programs/elderly-care'
      preLoaderRoute: typeof ProgramsElderlyCareRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/donate/verify': {
      id: '/donate/verify'
      path: '/verify'
      fullPath: '/donate/verify'
      preLoaderRoute: typeof DonateVerifyRouteImport
      parentRoute: typeof DonateRoute
    }
  }
}

interface DonateRouteChildren {
  DonateVerifyRoute: typeof DonateVerifyRoute
}

const DonateRouteChildren: DonateRouteChildren = {
  DonateVerifyRoute: DonateVerifyRoute,
}

const DonateRouteWithChildren =
  DonateRoute._addFileChildren(DonateRouteChildren)

interface ProgramsRouteChildren {
  ProgramsElderlyCareRoute: typeof ProgramsElderlyCareRoute
  ProgramsEmpowermentRoute: typeof ProgramsEmpowermentRoute
  ProgramsMotherlessHomeRoute: typeof ProgramsMotherlessHomeRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsElderlyCareRoute: ProgramsElderlyCareRoute,
  ProgramsEmpowermentRoute: ProgramsEmpowermentRoute,
  ProgramsMotherlessHomeRoute: ProgramsMotherlessHomeRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRouteWithChildren,
  ProgramsRoute: ProgramsRouteWithChildren,
  StoriesRoute: StoriesRouteWithChildren,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
